FROM node:18-alpine
WORKDIR /app/client_frontend
COPY client_frontend/package.json client_frontend/package-lock.json /app/client_frontend/
RUN npm install
COPY client_frontend /app/client_frontend
ENV HOST=0.0.0.0
ENV PORT=3000
EXPOSE 3000
CMD ["npm","start"]
